# telemt-deploy cluster LB — TCP passthrough for MTProto FakeTLS
# Generated by telemt-deploy — do not edit manually

global
    log /dev/log local0
    maxconn 4096
    daemon

defaults
    log global
    mode tcp
    option tcplog
    timeout connect 10s
    timeout client  1h
    timeout server  1h

frontend mtproto_front
    bind *:${LB_PORT}
    default_backend mtproto_nodes

backend mtproto_nodes
    balance source
    option tcp-check
${HAPROXY_SERVERS}
